# Generated by Django 3.2.4 on 2021-07-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('imagen', models.ImageField(upload_to='')),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('categorias', models.CharField(max_length=64)),
            ],
        ),
    ]
