# Generated by Django 3.2.4 on 2021-07-12 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20210711_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imagen',
        ),
    ]
